### PR TITLE
Added fix for non-string values

### PR DESCRIPTION
**Pull request by Zemistr**
This works too with classes with method __toString.

### CODE REVIEW

**Comment by JustBlackBird** [comment]
It's not a big deal but as for me
```php
return (string)$value;
```
is more readable than
```php
return "$value";
```

Also you should add test cases which need type casting.

**Comment by Zemistr** [comment]
Ok...sooo...better way is:

`array_unshift($args, (string)$value);`
and
`return (string)$value;`
?

**Comment by JustBlackBird** [comment]
Yes, I think so.

**Comment by Zemistr** [comment]
Ok, I can change the Pull Request :)

**Comment by Zemistr** [comment]
Done ;)

**Comment by fzerorubigd** [comment]
Could you please add a test case for this? a class with __toString() method as a context variable. 

Thank you!

**Comment by JustBlackBird** [comment]
@fzerorubigd is right, we're still waiting a test case...

**Pull request closed without merging**
