### PR TITLE
Fix handling of named arguments in partials

### PR DESCRIPTION
**Pull request by thormeier**
Also fix tests that weren't even executed.

Now constructs like `{{> partial foo=bar.baz }}` are also possible.

### CODE REVIEW

**Comment by thormeier** [comment]
Fixed :)

**Comment by JustBlackBird** [comment]
Thank you @thormeier !

**Comment by thormeier** [comment]
You're very welcome!

**Comment by mfeltscher** [comment]
Since I'm using partials with named arguments quite a lot it would be nice if you could release a new version (like 0.10.2) of the library. Would that be possible? :)

**Comment by JustBlackBird** [comment]
@mfeltscher, we definitely will release the new version but I'm not sure it will be done soon. At the meantime you can specify `dev-master` for composer's dependency instead of exact version.

**Comment by mfeltscher** [comment]
@JustBlackBird Due to minimum stability levels in our applications this is not possible. As for now I'm using a @thormeier's latest commit as my version but want to get rid of this as soon as possible.

**Comment by fzerorubigd** [comment]
@JustBlackBird I think its good idea to release the 0.10.2 for now. I don't see 0.11 in the next few month :)

**Comment by JustBlackBird** [comment]
@mfeltscher, @fzerorubigd done!

**Comment by fzerorubigd** [comment]
@JustBlackBird Thanks :)

**Comment by mfeltscher** [comment]
Thanks! :) cc: @thormeier

**Pull request merged**
