### PR TITLE
Fix slashes mess in Tokenizer

### LINKED ISSUE #113: No way to generate \\{{var}}
Correct result of (context is `['var' => 'value']`) : 

```
\\\{{var}}
````
is 
```
\value
```
but handlebars.php produce 
```
\\{{var}}
```

### PR DESCRIPTION
**Pull request by JustBlackBird**
I've tried to fix #113 with this PR.

### CODE REVIEW

**Comment by JustBlackBird** [comment]
It seems that I've missed one more use case. `\\\{{foo}}` should be evaluated `\\bar` instead of `\\{{foo}}` (see http://jsfiddle.net/6stcaud5/). Need more work here.

**Comment by JustBlackBird** [comment]
@fzerorubigd, it seems that I've fixed the issue. Could you please take a look?

**Comment by fzerorubigd** [comment]
Sure. I'm in a trip right now, I'll check it tomorrow.
Thanks!

**Comment by fzerorubigd** [comment]
@JustBlackBird thanks!

**Comment by JustBlackBird** [comment]
You're welcome!

**Pull request merged**
