### PR TITLE
@root special variable like in handlebars-v2.0.0.js

### PR DESCRIPTION
**Pull request by majortom731**
Hi,

I've built support for the @root special variable which allows to access to topmost context from anywhere within a template.

Please review and tell me what you think about it.

Regards

T.

### CODE REVIEW

**Comment by JustBlackBird** [comment]
As for me everything is fine. What do you think @fzerorubigd ?

**Comment by fzerorubigd** [comment]
Thank you. but please sqush commits into one. 
@JustBlackBird I think its ok, could you please review this?

**Comment by fzerorubigd** [comment]
@JustBlackBird Sorry :) I just see your comment :) thank you.

**Comment by majortom731** [comment]
Ok, seems I managed to squashed the 2 commits into one, but now Scrutinizer throws an error. ?

**Comment by fzerorubigd** [comment]
@majortom731 But there is 4 commit now. use `git rebase` or `git rebase --interactve` and the push result with `git push -f` in your repo.

**Comment by majortom731** [comment]
Working now?

**Comment by fzerorubigd** [comment]
@majortom731 Thank you!

**Pull request merged**
