### PR TITLE
add InlineLoader Class (import from Mustache PHP)

### PR DESCRIPTION
**Pull request by mai7star**
I import InlineLoader class from Mustache PHP.

### CODE REVIEW

**Comment by fzerorubigd** [comment]
thank you, but please provide some test for this.

**Comment by mai7star** [comment]
I wrote a test. (see tests/Xamin/HandlebarsTest.php)

**Comment by fzerorubigd** [comment]
@JustBlackBird __COMPILER_HALT_OFFSET__ is available only in the file that the __halt_compiler is available http://php.net/manual/en/function.halt-compiler.php

**Comment by mai7star** [comment]
thank you.

**Comment by fzerorubigd** [comment]
@mai7star you are welcome.

**Pull request merged**
